TARGET  := cross
HOST    := osx64

CC       := gcc
CXX      := g++
CFLAGS   := -O2 -Wall -DNDEBUG
CXXFLAGS := -O2 -Wall -DNDEBUG -std=c++11
LDFLAGS  :=
LDLIBS   :=

OBJECTS := $(patsubst %.cpp,%.o,$(wildcard src/*.cpp))

.PHONY: all clean

all: $(TARGET)

clean:
	$(RM) $(OBJECTS) $(TARGET)*

$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) $(CXXFLAGS) $(LDFLAGS) $(LDLIBS) -o $@
