TARGET  := cross.exe
HOST    := win64

CC       := x86_64-w64-mingw32-gcc
CXX      := x86_64-w64-mingw32-g++
CFLAGS   := -O2 -Wall -DNDEBUG
CXXFLAGS := -O2 -Wall -DNDEBUG -std=c++11
LDFLAGS  := -s -static
LDLIBS   :=

OBJECTS := $(patsubst %.cpp,%.o,$(wildcard src/*.cpp))

.PHONY: all clean

all: $(TARGET)

clean:
	$(RM) $(OBJECTS) $(TARGET)*

$(TARGET): $(OBJECTS)
	$(CXX) $(OBJECTS) $(CXXFLAGS) $(LDFLAGS) $(LDLIBS) -o $@
